### ISSUE TITLE
delete address while parcel still exists

### ISSUE THREAD

**Issue by gammastani** [FIPost/IPost#12]
problem:
you can delete an address while the parcel still exists.

**Comment by dirkvdw1** [comment]
adres wordt op inactief gesteld. Het pakket wordt wel opgeslagen met een locatieID.  Dit betekent dat de locatie altijd terug te vinden is ook al wordt het adres op inactief gesteld.
![afbeelding](https://user-images.githubusercontent.com/76440396/170027235-47cfefb0-95fb-49ae-b998-7ddc8da77e27.png)
